export const ERROR_CODES = {
  WEATHER_DATA_NOT_FOUND: "WEATHER_DATA_NOT_FOUND",
  WEATHER_UPSTREAM_INVALID_RESPONSE: "WEATHER_UPSTREAM_INVALID_RESPONSE",
  WEATHER_UPSTREAM_CLIENT_ERROR: "WEATHER_UPSTREAM_CLIENT_ERROR",
  WEATHER_UPSTREAM_TIMEOUT: "WEATHER_UPSTREAM_TIMEOUT",
  WEATHER_UPSTREAM_UNAVAILABLE: "WEATHER_UPSTREAM_UNAVAILABLE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
