name: Logic tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.x
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun test
