name: Logic tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WEATHERAPI_KEY: ${{ secrets.WEATHERAPI_KEY }}
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - name: Lint code
        run: bunx biome check --config-path .biomerc.json .
      - name: Run tests
        run: bun test
        if: ${{ env.WEATHERAPI_KEY != '' }}
